name = "main"
version = "1.0.0"

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
gleam_http = "~> 3.7.0"
gleam_httpc = "~> 4.0.0"
gleam_json = "~> 2.3.0"
gleam_javascript = "~> 0.13.0"
envoy = ">= 1.0.1 and < 2.0.0"
argv = ">= 1.0.2 and < 2.0.0"
