[package]

name = "core"
version = "0.0.1"
authors = [ "Romain Prignon pro.rprignon@gmail.com" ]

#[lib]
#path = "./lib.rs"

[[bin]]
name = "emoji"
path = "./lib.rs"

[dependencies]
hyper = "0.12"
http = "0.1"